# Generated by Django 3.1.4 on 2021-02-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id_invest', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id_registo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=30)),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.conta')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Planeamento',
            fields=[
                ('id_planeamento', models.AutoField(primary_key=True, serialize=False)),
                ('montante_limite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prazo', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id_alert', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField()),
                ('montante', models.DecimalField(decimal_places=2, max_digits=30)),
                ('montanteLimite', models.DecimalField(decimal_places=2, max_digits=30)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_planeamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.invest')),
                ('id_sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
    ]
