# Generated by Django 3.1.4 on 2021-01-18 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=35, unique=True)),
                ('idade', models.IntegerField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000)),
                ('tipo', models.CharField(max_length=20)),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=30)),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.conta')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Planeamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante_limite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prazo', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero', models.IntegerField()),
                ('data', models.DateField()),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField()),
                ('montante', models.DecimalField(decimal_places=2, max_digits=30)),
                ('montanteLimite', models.DecimalField(decimal_places=2, max_digits=30)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_planeamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.invest')),
                ('id_sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
