# Generated by Django 3.1.4 on 2020-12-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSaveIt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil')),
            ],
        ),
    ]
