# Generated by Django 3.1.4 on 2021-01-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSaveIt', '0002_auto_20210119_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='planeamento',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='registo',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil'),
        ),
    ]
