# Generated by Django 3.1.4 on 2020-12-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSaveIt', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Planeamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante_limite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prazo', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.categoria')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.perfil')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSaveIt.subcategoria')),
            ],
        ),
    ]
