# Generated by Django 3.1.4 on 2021-01-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSaveIt', '0004_auto_20210120_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ultimo_nome',
        ),
    ]
